name = "hafiportrait"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "hafiportrait"

[env.production.vars]
ENVIRONMENT = "production"

# Environment variables will be set via Cloudflare Dashboard
#[vars]
#ENVIRONMENT = "production"

[env.preview]
name = "hafiportrait-preview"
# Variabel khusus untuk preview
[env.preview.vars]
ENVIRONMENT = "preview"
